<div id="define-terms" title="Definition of Terms">
<form name="defForm">
<b>Consensus Genotype</b> - When the same line and marker is measured in multiple genotype experiments a consensus genotype is calculated using majority rule. If there is no majority then the value is set to missing.<br>
<b>Genotype Experiment</b> - Genotypes measured for a set of lines and markers using a common platform (Infinium, GoldenGate, Sequenom, etc). A list of all genotype experiment and links to their description can be found in <a href="t3_report.php?query=GTrials" target="_new">List of Genotype Experiments</a>.
</form>
</div>
