<div id="define-terms" title="Definition of Terms" style="display:none;">
<form name="defForm">
<b>Genotype Consensus</b> - When the same line and marker is measured in multiple genotype experiments a consensus genotype is calculated using majority rule. If there is no majority then the value is set to missing.<br><br>
<b>Genotype Experiment</b> - Genotypes measured for a set of lines and markers using a common platform (Infinium, GoldenGate, Sequenom, etc). A list of all genotype experiment and links to their description can be found in List of <a id="input" href="t3_report.php?query=GTrials" target="_new">Genotype Experiments</a>.<br><br>
<b>Genetic Maps</b> - If no genetic map is selected then the marker chromosome is set to 0 and position is sequentially incremented. Markers with no map are not excluded.<br><br>
<b>Note</b>: Genotype data for genotype experiments with over 100K markers can only be downloaded as a single experiment. 
Markers with no map location are assigned to chromosome 0. 
List of <a href="genotyping/genotype_selection.php">Genotype Experiments</a>.
</form>
</div>
