<?php
require 'config.php';
include($config['root_dir'].'includes/bootstrap.inc');
include($config['root_dir'].'theme/normal_header.php');
?>
<h1>About T3</h1>

<h3>Project Description</h3>
<div class="section">
<p>T3 is the web portal for the data generated by the <a href="http://triticeaecap.org/">Triticeae Coordinated Agricultural Project</a> (CAP), funded by the National Institute for Food and Agriculture (NIFA) of the United States Department of Agriculture (USDA). T3 contains SNP, phenotypic, and pedigree data from wheat and barley germplasm in the Triticeae CAP.  It is intended to serve as a source of input data for plant breeders to use for marker-based association mapping and genomic selection of desired crop traits.
</div>

<h3>Data Access Policy</h3>
  <div class="section">
  <p>Triticeae CAP data on T3 will be made public within X months of submission. In the interim, these data will only be available to members of the Triticeae CAP unless explicitly released by the data creators.</p>
  </div>

<h3>T3 Team</h3>
<div class="section">
<style type="text/css">
#thtteamtbl td{text-align:left}
.strong{font-weight:bold}
</style>
<table id="thtteamtbl" border="0" cellpadding="0" cellspacing="0">
<thead>
<tr>
<th>Name</th><th>Affiliation</th>
</tr>
</thead>
<tbody>
  <tr><td class="strong">Jean-Luc Jannink</td><td>USDA-ARS, Cornell University</td></tr>
  <tr><td class="strong">Mark Sorrells</td><td>Department of Plant Breeding and Genetics, Cornell University</td></tr>
  <tr><td class="strong">Peter Bradbury</td><td>USDA-ARS, Cornell University</td></tr>
  <tr><td class="strong">Dave Matthews</td><td>USDA-ARS, Cornell University</td></tr>
  <tr><td class="strong">John Lee</td><td>USDA-ARS, Western Regional Research Center, Albany CA</td></tr>
  <tr><td class="strong">Dave Hane</td><td>University of California, Davis</td></tr>
</tbody></table>
</div>

<h3>Origin</h3>
<div class="section">
<p>
  T3 was developed as "The Hordeum Toolbox" (THT) from 2006 to 2010 for the 
  <a href="http://barleycap.org">Barley CAP</a> project.  The creation team was as
follows.
<table id="thtteamtbl" border="0" cellpadding="0" cellspacing="0">
<thead>
<tr>
<th>Name</th><th>Affiliation</th><th>Role</th>
</tr>
</thead>
<tbody>
<tr><td class="strong">Julie A. Dickerson</td><td>Electrical and Computer Engineering, Iowa State University</td><td>Principal Investigator</td></tr>
<tr><td class="strong">Roger P. Wise</td><td>USDA-ARS<br/>Department of Plant Pathology<br/>Iowa State University</td><td>Principal Investigator</td></tr>
<tr><td class="strong">Shreyartha Mukherjee</td><td>Bioinformatics and Computational Biology, Iowa State University</td><td>Developer/Bioinformatics</td></tr>
<tr><td class="strong">Kartic Ramesh</td><td>Computer Science, Iowa State University</td><td>Developer</td></tr>
<tr><td class="strong">Gavin Monroe</td><td>Software Engineering, Iowa State University</td><td>Developer</td></tr>
<tr><td class="strong">Ethan Wilder</td><td>Computer Engineering, Iowa State University</td><td>Developer (Alumnus)</td></tr>
<tr><td class="strong">Yong Huang</td><td>Bioinformatics and Computational Biology, Iowa State University</td><td>Developer/Bioinformatics (Alumnus)</td></tr>
<tr><td class="strong">Jennifer Kling</td><td>Dept. of Crop and Soil Science Oregon State University</td><td>Phenotype and pedigree data curation </td></tr>
<tr><td class="strong">Shiaoman Chao</td><td>USDA-ARS Biosciences Research Lab, Fargo, ND</td><td>SNP data production and curation</td></tr>
<tr><td class="strong">Tim Close</td><td>Botany and Plant Sciences<br/>University of California<br/>Riverside, CA</td><td>Assembly and SNP context information from <a href="http://harvest.ucr.edu/" title="">HarvEST: Barley</a></td></tr>
<tr><td class="strong">Peter Bradbury</td><td>USDA-ARS, Cornell University, Ithaca, NY</td><td>Pedigree information and links to <a href="http://www.maizegenetics.net/index.php?page=bioinformatics/tassel/index.html" title="">TASSEL</a></td></tr>
</tbody>
</table>
</p>
</div>

</div>
<?php include($config['root_dir'].'theme/footer.php');?>
