<?php
// colors from R col2rgb(heat.colors(16));
$color[0] = '#ff0000';
$color[1] = '#ff1700';
$color[2] = '#ff2e00';
$color[3] = '#ff4600';
$color[4] = '#ff5d00';
$color[5] = '#ff7400';
$color[6] = '#ff8b00';
$color[7] = '#ffa200';
$color[8] = '#ffb900';
$color[9] = '#ffd100';
$color[10] = '#ffe800';
$color[11] = '#ffff00';
$color[12] = '#ffff20';
$color[13] = '#ffff60';
$color[14] = '#ffff9f';
$color[15] = '#ffffdf';
?>
