<!-- <link rel="stylesheet" type="text/css" href="/gbrowse/gbrowse.css" /> -->
<link rel="stylesheet" type="text/css" href="./gbrowse/tracks.css" />
<link rel="stylesheet" type="text/css" href="./gbrowse/titlebar-default.css" />

<script src="./jquery.js" type="text/javascript"></script>
<script type="text/javascript">
var $j = jQuery.noConflict();
</script>
<script src="./gbrowse/js/buttons.js" type="text/javascript"></script>
<script src="./gbrowse/js/prototype.js" type="text/javascript"></script>
<script src="./gbrowse/js/yahoo-dom-event.js" type="text/javascript"></script>
<script src="./js/balloon.config.js" type="text/javascript"></script>
<script src="./js/balloon.js" type="text/javascript"></script>
<script src="./gbrowse/js/rubber.js" type="text/javascript"></script>
<script src="./gbrowse/js/overviewSelect.js" type="text/javascript"></script>
<script src="./gbrowse/js/detailSelect.js" type="text/javascript"></script>
<script src="./gbrowse/js/scriptaculous.js" type="text/javascript"></script>
<script src="./gbrowse/js/bookmark.js" type="text/javascript"></script>
<script src="./gbrowse/js/toggle.js" type="text/javascript"></script>
<script src="./js/gbrowse-utils.js" type="text/javascript"></script>
